### ISSUE TITLE
Silikujo requires me to close the window twice to close it

### ISSUE THREAD

**Issue by chl0e3e** [vdamewood/siliko#3]
### Environment
Debian 11 on WSL2
GTK 4.9.1
VcXsrv
Windows 10

### Issue
Silikujo does not close after the first attempt when the close button is pressed. After pressing close once, the window reappears. When using the program after that, the program will cause a "Segmentation fault". If the program is closed again before another input is tried, the program closes down correctly.

### gdb backtrace
```
user@DESKTOP-AVLTLKA:~/tmp/build/siliko$ gdb ./products/Silikujo
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./products/Silikujo...
(gdb) r
Starting program: /home/user/tmp/build/siliko/products/Silikujo
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff5851700 (LWP 28025)]
[Detaching after fork from child process 28026]
[New Thread 0x7ffff5050700 (LWP 28027)]
[Thread 0x7ffff5050700 (LWP 28027) exited]
[New Thread 0x7ffff5050700 (LWP 28028)]
[New Thread 0x7fffec9f1700 (LWP 28029)]
[New Thread 0x7fffe2f01700 (LWP 28030)]
[New Thread 0x7fffe2700700 (LWP 28031)]
[New Thread 0x7fffe1eff700 (LWP 28032)]
[New Thread 0x7fffe16fe700 (LWP 28033)]
[New Thread 0x7fffe0efd700 (LWP 28034)]
[New Thread 0x7fffcbfff700 (LWP 28035)]
[New Thread 0x7fffcb7fe700 (LWP 28036)]
[New Thread 0x7fffcaffd700 (LWP 28037)]
[New Thread 0x7fffca7fc700 (LWP 28038)]
[New Thread 0x7fffc9ffb700 (LWP 28039)]
[New Thread 0x7fffc97fa700 (LWP 28040)]
[New Thread 0x7fffc8ff9700 (LWP 28041)]
[New Thread 0x7fffa7fff700 (LWP 28042)]
[New Thread 0x7fffa77fe700 (LWP 28043)]
[New Thread 0x7fffa6ffd700 (LWP 28044)]
[New Thread 0x7fffa67fc700 (LWP 28045)]
[New Thread 0x7fffa5ffb700 (LWP 28046)]
[New Thread 0x7fffa57fa700 (LWP 28047)]
[New Thread 0x7fffa4ff9700 (LWP 28048)]
[New Thread 0x7fff87fff700 (LWP 28049)]
[New Thread 0x7fff877fe700 (LWP 28050)]
[New Thread 0x7fff86ffd700 (LWP 28051)]
[New Thread 0x7fff867fc700 (LWP 28052)]
[Detaching after fork from child process 28053]
[New Thread 0x7fff85ffb700 (LWP 28054)]
[Detaching after fork from child process 28055]
[Detaching after fork from child process 28056]
[Detaching after fork from child process 28057]
[Detaching after fork from child process 28058]
[Detaching after fork from child process 28059]
[Detaching after fork from child process 28060]
[Detaching after fork from child process 28061]
[Detaching after fork from child process 28062]
[Detaching after fork from child process 28063]
[Detaching after fork from child process 28064]
[Detaching after fork from child process 28065]
[Detaching after fork from child process 28066]
[Detaching after fork from child process 28067]
[Detaching after fork from child process 28068]
[New Thread 0x7fff857fa700 (LWP 28069)]
[New Thread 0x7fff84ff9700 (LWP 28070)]
[Thread 0x7fff857fa700 (LWP 28069) exited]
[Thread 0x7fff84ff9700 (LWP 28070) exited]
[New Thread 0x7fff84ff9700 (LWP 28071)]
[New Thread 0x7fff84ff9700 (LWP 28072)]
[Thread 0x7fff84ff9700 (LWP 28071) exited]
[Thread 0x7fff84ff9700 (LWP 28072) exited]
[Detaching after fork from child process 28073]
[Detaching after fork from child process 28074]
[Detaching after fork from child process 28075]
[Detaching after fork from child process 28076]
[Detaching after fork from child process 28077]
[Detaching after fork from child process 28078]
[Detaching after fork from child process 28079]
[Detaching after fork from child process 28080]

(Silikujo:28021): GLib-GObject-CRITICAL **: 17:04:08.310: invalid unclassed pointer in cast to 'GtkBuilder'

(Silikujo:28021): Gtk-CRITICAL **: 17:04:08.310: gtk_builder_get_object: assertion 'GTK_IS_BUILDER (builder)' failed

(Silikujo:28021): Gtk-CRITICAL **: 17:04:08.310: gtk_editable_get_text: assertion 'GTK_IS_EDITABLE (editable)' failed

Thread 1 "Silikujo" received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
74      ../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
(gdb) bt 100
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:74
#1  0x00007ffff7445f2f in __GI___strdup (s=0x0) at strdup.c:41
#2  0x00007ffff7fc58c4 in SilikoStringSourceNew (NewInput=0x0) at /home/user/siliko/siliko/src/StringSource.c:72
#3  0x0000555555555482 in Calculate (Widget=0x555555958970, EvalWindow=0x5555558e5a50) at /home/user/siliko/silikujo-unix/EvalWindow.c:32
#4  0x00007ffff75c2569 in _g_closure_invoke_va (closure=closure@entry=0x5555558d9b90, return_value=return_value@entry=0x0, instance=instance@entry=0x555555958970, args=args@entry=0x7fffffffcb98, n_params=0,
    param_types=0x0) at ../gobject/gclosure.c:895
#5  0x00007ffff75dac1c in g_signal_emit_valist (instance=0x555555958970, signal_id=135, detail=0, var_args=var_args@entry=0x7fffffffcb98) at ../gobject/gsignal.c:3456
#6  0x00007ffff75dae12 in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../gobject/gsignal.c:3606
#7  0x00007ffff789f932 in _gtk_marshal_VOID__INT_DOUBLE_DOUBLEv (closure=closure@entry=0x555555959810, return_value=return_value@entry=0x0, instance=instance@entry=0x555555959750,
    args=args@entry=0x7fffffffce88, marshal_data=marshal_data@entry=0x0, n_params=n_params@entry=3, param_types=0x5555558a8170) at gtk/gtkmarshalers.c:5445
#8  0x00007ffff75c2569 in _g_closure_invoke_va (closure=closure@entry=0x555555959810, return_value=return_value@entry=0x0, instance=instance@entry=0x555555959750, args=args@entry=0x7fffffffce88, n_params=3,
    param_types=0x5555558a8170) at ../gobject/gclosure.c:895
#9  0x00007ffff75dac1c in g_signal_emit_valist (instance=0x555555959750, signal_id=92, detail=0, var_args=var_args@entry=0x7fffffffce88) at ../gobject/gsignal.c:3456
#10 0x00007ffff75dae12 in g_signal_emit (instance=instance@entry=0x555555959750, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3606
#11 0x00007ffff79462e5 in gtk_gesture_click_end (gesture=gesture@entry=0x555555959750, sequence=sequence@entry=0x0) at ../gtk/gtkgestureclick.c:275
#12 0x00007ffff75c513b in g_cclosure_marshal_VOID__BOXEDv (closure=0x5555558b9430, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>,
    n_params=<optimized out>, param_types=0x5555558b9460) at ../gobject/gmarshal.c:1686
#13 0x00007ffff75c2569 in _g_closure_invoke_va (closure=closure@entry=0x5555558b9430, return_value=return_value@entry=0x0, instance=instance@entry=0x555555959750, args=args@entry=0x7fffffffd1e8, n_params=1,
    param_types=0x5555558b9460) at ../gobject/gclosure.c:895
#14 0x00007ffff75dac1c in g_signal_emit_valist (instance=0x555555959750, signal_id=87, detail=0, var_args=var_args@entry=0x7fffffffd1e8) at ../gobject/gsignal.c:3456
#15 0x00007ffff75dae12 in g_signal_emit (instance=instance@entry=0x555555959750, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3606
#16 0x00007ffff7943507 in _gtk_gesture_set_recognized (sequence=0x0, recognized=0, gesture=0x555555959750) at ../gtk/gtkgesture.c:340
#17 _gtk_gesture_check_recognized (gesture=gesture@entry=0x555555959750, sequence=sequence@entry=0x0) at ../gtk/gtkgesture.c:381
#18 0x00007ffff7944b9b in gtk_gesture_handle_event (y=9.0000009536743164, x=36.000003814697266, event=0x55555afa7dc0, controller=0x555555959750) at ../gtk/gtkgesture.c:684
#19 gtk_gesture_handle_event (controller=0x555555959750, event=0x55555afa7dc0, x=36.000003814697266, y=9.0000009536743164) at ../gtk/gtkgesture.c:607
#20 0x00007ffff794781e in gtk_gesture_single_handle_event (controller=0x555555959750, event=0x55555afa7dc0, x=36.000003814697266, y=9.0000009536743164) at ../gtk/gtkgesturesingle.c:230
#21 0x00007ffff7918466 in gtk_event_controller_handle_event (controller=controller@entry=0x555555959750, event=event@entry=0x55555afa7dc0, target=target@entry=0x555555959c30, x=x@entry=36.000003814697266,
    y=y@entry=9.0000009536743164) at ../gtk/gtkeventcontroller.c:362
#22 0x00007ffff7a50f27 in gtk_widget_run_controllers (widget=widget@entry=0x555555958970, event=event@entry=0x55555afa7dc0, target=target@entry=0x555555959c30, x=36.000003814697266, y=9.0000009536743164,
    phase=phase@entry=GTK_PHASE_CAPTURE) at ../gtk/gtkwidget.c:4530
#23 0x00007ffff7a583b1 in _gtk_widget_captured_event (widget=widget@entry=0x555555958970, event=event@entry=0x55555afa7dc0, target=target@entry=0x555555959c30) at ../gtk/gtkwidget.c:4693
#24 0x00007ffff797f0a6 in gtk_propagate_event_internal (widget=0x555555958970, widget@entry=0x555555959c30, event=event@entry=0x55555afa7dc0, topmost=<optimized out>) at ../gtk/gtkmain.c:1911
#25 0x00007ffff797f1e5 in gtk_propagate_event (widget=widget@entry=0x555555959c30, event=event@entry=0x55555afa7dc0) at ../gtk/gtkmain.c:1993
#26 0x00007ffff797f743 in gtk_main_do_event (event=0x55555afa7dc0) at ../gtk/gtkmain.c:1685
#27 0x00007ffff7a6448c in surface_event (surface=surface@entry=0x55555595c920, event=<optimized out>, widget=widget@entry=0x55555589a7b0) at ../gtk/gtkwindow.c:4736
#28 0x00007ffff7bb2359 in _gdk_marshal_BOOLEAN__POINTER (closure=closure@entry=0x55555a43f430, return_value=return_value@entry=0x7fffffffd7b0, n_param_values=n_param_values@entry=2,
    param_values=param_values@entry=0x7fffffffd860, invocation_hint=invocation_hint@entry=0x7fffffffd800, marshal_data=marshal_data@entry=0x0) at gdk/gdkmarshalers.c:258
#29 0x00007ffff7c183df in gdk_surface_event_marshaller (closure=0x55555a43f430, return_value=0x7fffffffd7b0, n_param_values=2, param_values=0x7fffffffd860, invocation_hint=0x7fffffffd800, marshal_data=0x0)
    at ../gdk/gdksurface.c:435
#30 0x00007ffff75c233f in g_closure_invoke (closure=0x55555a43f430, return_value=return_value@entry=0x7fffffffd7b0, n_param_values=2, param_values=param_values@entry=0x7fffffffd860,
    invocation_hint=invocation_hint@entry=0x7fffffffd800) at ../gobject/gclosure.c:832
#31 0x00007ffff75d476b in signal_emit_unlocked_R (node=<optimized out>, detail=detail@entry=0, instance=instance@entry=0x55555595c920, emission_return=emission_return@entry=0x7fffffffd940,
    instance_and_params=instance_and_params@entry=0x7fffffffd860) at ../gobject/gsignal.c:3796
#32 0x00007ffff75da4e5 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffd9f8) at ../gobject/gsignal.c:3559
#33 0x00007ffff75dae12 in g_signal_emit (instance=instance@entry=0x55555595c920, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3606
#34 0x00007ffff7c1b8b6 in gdk_surface_handle_event (event=event@entry=0x55555afa7dc0) at ../gdk/gdksurface.c:2946
#35 0x00007ffff7c03eae in _gdk_event_emit (event=0x55555afa7dc0) at ../gdk/gdkevents.c:493
#36 0x00007ffff7bebd6a in gdk_event_source_dispatch (source=<optimized out>, callback=<optimized out>, user_data=<optimized out>) at ../gdk/x11/gdkeventsource.c:425
#37 0x00007ffff70dd6db in g_main_dispatch (context=0x555555575db0) at ../glib/gmain.c:3444
#38 g_main_context_dispatch (context=0x555555575db0) at ../glib/gmain.c:4162
#39 0x00007ffff70dd968 in g_main_context_iterate (context=context@entry=0x555555575db0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4238
--Type <RET> for more, q to quit, c to continue without paging--
#40 0x00007ffff70dda0f in g_main_context_iteration (context=context@entry=0x555555575db0, may_block=may_block@entry=1) at ../glib/gmain.c:4303
#41 0x00007ffff76e4975 in g_application_run (application=0x555555572b70, argc=-9188, argv=<optimized out>) at ../gio/gapplication.c:2571
#42 0x000055555555540f in main (argc=1, argv=0x7fffffffdd88) at /home/user/siliko/silikujo-unix/Main.c:38
```

**Comment by vdamewood** [comment]
Bug fixed in commit 39ea3c8947992af210126cda1ce4e110292a2eba merged into trunk.
